=== Fundamentals

In order to perform DNSSEC based validations in zone delegations additional
security data (i.e. keys) need to be provided within the corresponding zones.

Therefore, the Key Signing Key (KSK) of the delegated zone reflects the major Secure Entry Point (SEP).
This key is placed within the DNSKEY RRSet of the delegated zone which is signed by the key, too.
Besides, the key's fingerprint is placed as DS RR (Delegation Signer Resource Record) on higher
delegation levels to avoid additional resource consumption. 

All public key related data is provided as DNSKEY RR in wire-text-format. The max number
of possible keys in check requests is limited to 5. Within zone signging procedure all
signatures and DS RRs are generated for each KSK automatically and are distributed with
the delegated zone finally.

=== DNSKEY Resource Record

Each DNSKEY RR is provided as wire-text-format described in https://www.ietf.org/rfc/rfc4034.txt[RFC4034]
and shown below:

                    1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 3 3 
0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|              Flags            |    Protocol   |   Algorithm   |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ 
/                                                               /
/                          Public Key                           /
/                                                               /
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+

The Flag's field covers the bits for DNSKEY related ZONE, REVOKE and SEP settings.
The Field Algorhitm covers the keys cryptographic format. The Public Key part is keept
as last field within RR.

=== DNSKEY Types & Signing

Introducing DS RR within https://www.ietf.org/rfc/rfc3658.txt[RFC3658] recommends paired separation
between the Zone Signing Key (ZSK) and the Key Signing Key (KSK). While a ZSK is used to sign any record
data within zone (excluding DNSKEY RRSet), the KSK is used to authenticate ZSK by signing it's
corresponding DNSKEY RRSet. Hence, changing the ZSK implies less effort while changing the KSK leads to
further changes on higher leveled zones. Therefore, a KSK reflects larger keys than a ZSK to ensure
longer periods of usage. This also suites less consumption of zone data and finally smaller package
sizes in dns responses as explained in https://www.ietf.org/rfc/rfc4641.txt[RFC4641].
Hence, the separation of keys improves security, resource consumption as well as flexibility in key
management but leads to a higher complexity in the DNS protocol, too
For that reason, key separation is not mandatory and usage of a single key instead of key pairs is
possible in DNSSEC. Usually common use cases as ZSK+KSK and ZSK=KSK are feasible.
Nevertheless, any key used for DNSSEC related zone signing must be covered within DNSKEY RRSet.

=== DNSKEY RR Visibility

The notion visible DNSKEY RR is defined as follows:
Any given DNSKEY RR of check request that is covered by the DNSKEY RRSet of the delegated zone
is visible.

=== Validation Concept

Within DNSSEC validation _Proof of Possession_ and _Chain of Trust_ must be satisfied and
considered as follows.

_Proof of Possession:_ The check request contains at least one public signing key (i.e. KSK) that
validates the signature of the delegated zone's DNSKEY RRSet. This ensures integrity and authenticity
of the DNSKEY RRSet themselves.

_Chain of Trust:_ The check request or the DNSKEY RRSet contains at least one public signing key
(i.e. ZSK) that validates the signature of the delegated zone's SOA RR. Further trust verification
on higher zone levels is not considered.

Based on this, corresponding criteria are defined in <<Requirements>>.

=== Requirements

As a first step in DNSSEC related predelagation checks the DNSKEY RRs of request are pre-checked
according the key format correctness (i.e. flags, algorithm, public key etc.). In the second step
further checks across zones and nameservers are carried out.

[[req:dnskey-parameters,DNSKEY: Parameters]]
==== DNSKEY: Parameters
All DNSKEY RRs of the request **MUST** be distinct. Hence, the key's field parameter **MUST**
be unique among all other keys. Besides, a maximum of 5 DNSKEY RR can be handed over in a request.
Otherwise a corresponding **ERROR** is issued.

**ERROR**:
[cols="1,6"]
|===
|Code |Message

| 208
| Duplicate DNSKEY RR

| 210
| Max 5 DNSKEY RR allowed
|===

==== DNSKEY: Flags

The flags field is specified as single numeric value in range of [0,65535] and
shall match the following requirements. 

[[req:dnskey-flags-zone-bit,ZONE Bit]]
===== ZONE Bit
Bit 7 (ZONE) **MUST** be SET. Otherwise **ERROR**.

**ERROR**:
[cols="1,6"]
|===
|Code |Message

| 200
| DNSKEY RR ZONE flag (bit 7) must be set
|===

**Further explanation:**
This requirement is specified in https://www.ietf.org/rfc/rfc4034.txt[RFC4034].

[[req:dnskey-flags-revoke-bit,REVOKE Bit]]
===== REVOKE Bit
Bit 8 (REVOKE) **MUST** not be set. Otherwise **ERROR**.

**ERROR**:
[cols="1,6"]
|===
|Code |Message

| 201
| DNSKEY RR REVOKE flag (bit 8) must not be set
|===

**Further explanation:**
Revoked keys cannot be used as trust anchors as described in https://www.ietf.org/rfc/rfc5011.txt[RFC5011].

[[req:dnskey-flags-sep-bit,SEP Bit]]
===== SEP Bit
Bit 15 (SEP) **SHOULD** be set. Otherwise a **WARNING** is returned.

**WARNING**:
[cols="1,6"]
|===
|Code |Message

| 202
| DNSKEY RR SEP flag (bit 15) should be set
|===

[[req:dnskey-flags-values,Final Values]]
===== Final Values
According to the former requirements <<ZONE Bit>>, <<REVOKE Bit>> and <<SEP Bit>> a numeric value
out of [256,257] **MUST** be choosen. All other values result in **ERROR**.

**ERROR**:
[cols="1,6"]
|===
|Code |Message

| 221
| Unknown flags in DNSKEY RR are set
|===

==== DNSKEY: Protocol

The protocol's field is considered as an immutable value of 3 as specified in
https://www.ietf.org/rfc/rfc2308.txt[RFC4034]. Hence, no **WARNINGs** or **ERRORs** are issued.

[[req:dnskey-algo,DNSKEY: Algorithm]]
==== DNSKEY: Algorithm
The algorithm's cryptographic field value **MUST** be chosen according to the following subset list
of https://www.iana.org/assignments/dns-sec-alg-numbers/dns-sec-alg-numbers.xhtml[IANA-Registry].

Supported Algorithms: 3, 5, 6, 7, 8, 10, 12, 13 ,14, 15 and 16

Any violation of this requirement results in **ERROR**.

**ERROR**:
[cols="1,6"]
|===
|Code |Message

| 220
| DNSKEY RR has invalid algorithm
|===

**REMARK:** Algorithms 3, 5, 7 and 12 are _deprecated_ and future support will end in upcoming
releases.

[[req:dnskey,DNSKEY: Public Key]]
==== DNSKEY: Public Key
The public key field **MUST** cover the base64 encoded key value. Otherwise **ERROR**.

**ERROR**:
[cols="1,6"]
|===
|Code |Message

| 207
| DNSKEY RR public key must be base64 encoded
|===

Furthermore, the internal key format depends on the selected cryptographic algorhitm and enforces
specific requirements as shown below.

===== RSA

The RSA related algorithms 5,7,8 and 10 cover the requirements below.

[[req:dnskey-alg-rsa-modulos,Modulos]]
====== Modulos
The modulo's bit length **MUST** be in range of [512,4096]. Otherwise **ERROR**.

**ERROR**:
[cols="1,6"]
|===
|Code |Message

| 203
| DNSKEY RR RSA key modulus length in bits out of range
|===

[[req:dnskey-alg-rsa-exponent,Exponent]]
====== Exponent
The exponent's max bit length **MUST** be less than 128. Otherwise **ERROR**.

**ERROR**:
[cols="1,6"]
|===
|Code |Message

| 204
| DNSKEY RR RSA public key exponent length in bits must not exceed 128 bits
|===

**Further explanation:** The ranges for <<Modulos>> and <<Exponent>> are specified
in http://www.ietf.org/rfc/rfc3110.txt[RFC3110].


===== DSA

DSA based algorithms 3 and 6 consider the requirements below.

[[req:dnskey-alg-dsa-t,T Parameter]]
====== T Parameter
The T parameter **MUST** be in range of [0,8]. Otherwise **ERROR**.

**ERROR**:
[cols="1,6"]
|===
|Code |Message

| 205
| DNSKEY RR DSA public key parameter T out of range
|===

[[req:dnskey-alg-dsa-length,Length]]
====== Length
The byte length must be equal to (213+T*24). Otherwise **ERROR**.

**ERROR**:
[cols="1,6"]
|===
|Code |Message

| 206
| DNSKEY RR DSA public key has invalid size
|===

[[req:dnskey-alg-ecdsa,ECDSA]]
===== ECDSA
The ECDSA algorithm 13 and 14 differ in key's bit length:

* In ECDSAP256SHA256 (13) the bit length **MUST** be 512. Otherwise **ERROR**.
* In ECDSAP384SHA384 (14) the bit length **MUST** be 768. Otherwise **ERROR**.

**ERROR**:
[cols="1,6"]
|===
|Code |Message

| 226
| DNSKEY RR ECDSA public key has invalid size
|===

**Furtner explanation:** All length parameter are specified in http://www.ietf.org/rfc/rfc6605.txt[RFC6605].

[[req:dnskey-alg-gost,GOST]]
===== GOST
The key bit length of algorithm 12 **MUST** be 512. Otherwise **ERROR**.  

**ERROR**:
[cols="1,6"]
|===
|Code |Message

| 227
| DNSKEY RR GOST public key has invalid size
|===

**Furtner explanation:** All length parameter are specified in http://www.ietf.org/rfc/rfc5933.txt[RFC5933].

[[req:dnskey-alg-eddsa,EdDSA]]
===== EdDSA
The EdDSA algorithm 15 and 16 differ in key's bit length:

* In ED25519 (15) the bit length **MUST** be 256. Otherwise **ERROR**.
* In ED448 (16) the bit length **MUST** be 456. Otherwise **ERROR**.

**ERROR**:
[cols="1,6"]
|===
|Code |Message

| 228
| DNSKEY RR ED public key has invalid size
|===

**Furtner explanation:** All length parameter are specified in http://www.ietf.org/rfc/rfc8080.txt[RFC8080].

==== DNSKEY RRSet

[[req:dnskey-rrset-status,Status]]
===== Status
The DNSKEY RRSet of the delegated zone **MUST** be identical on all authoritative nameservers.
Otherwise **ERROR**.

**ERROR**:
[cols="1,6"]
|===
|Code |Message

| 211
| Inconsistent DNSKEY RR in nameserver response
|===

[[req:dnskey-rrset-visibility,Visibility]]
===== Visibility
At least one DNSKEY RR of request **MUST** be <<DNSKEY RR Visibility,VISIBLE>> within the DNSKEY RRSet.
Otherwise **ERROR**.

**ERROR**:
[cols="1,6"]
|===
|Code |Message

| 213
| Did not find any DNSKEY RR from request in all nameserver responses
|===

Besides, for any invisible DNSKEY RR of request a **WARNING** is returned.

**WARNING**:
[cols="1,6"]
|===
|Code |Message

| 212
| Did not find DNSKEY RR from request in all nameserver responses
|===

**Further explanation:**
Additional DNSKEY RR in RRSet are neglected and accordance in DNSKEY RRSet signature
is assumed but not tested explicitly. This allows online signing for DSA and ECDSA based
algorithms.

[[req:dnssec-proof-of-possession,Validation Proof of Possession]]
==== Validation Proof of Possession
At least one visible DNSKEY RR of request **MUST** validate the signature of the DNSKEY RRSet.
Otherwise **ERROR**.

**ERROR**:
[cols="1,6"]
|===
|Code |Message

| 216
| No visible DNSKEY found signing the DNSKEY RR obtained in response
|===

**Further explanation:**
This requirement enforces named proof of possession of section <<Validation Concept>>.

[[req:dnssec-chain-of-trust,Validation Chain of Trust]]
==== Validation Chain of Trust
For the SOA RR of the delegated zone a valid chain of trust **MUST** exist. This means at least one
visible DNSKEY RR of request or within the DNSKEY RRSet must validate the signature of the SOA RR.
Otherwise **ERROR**.

**ERROR**:
[cols="1,6"]
|===
|Code |Message

| 217
| No visible DNSKEY found in signing directly or indirectly the SOA RR obtained in response
|===

**Further explanation:**
This requirement enforces <<Validation Concept, chain of trust>> towards the delegated zone
and prevents security lameness. Trust validation is limited to delegated zone level to allow
predelgation check for unregistered domains, too.

==== Cross Checks

According to the grouped DNSSEC requirements of the aforementioned sections further cross requirements
can be derived.

[[req:dnssec-cross-edns0,EDNS0 Support]]
===== EDNS0 Support 
All authoritative nameservers **MUST** support the EDNS0 protocol. Hence, nameservers
**MUST** respond with DNSSEC data (i.e signatures) towards DO-Bit signed queries.
Otherwise **ERROR**.

**ERROR**:
[cols="1,6"]
|===
|Code |Message

| 218
| Received invalid answer to a DO-Bit query 
|===

[[req:dnssec-cross-udp,UDP related EDNS0]]
===== UDP related EDNS0 
All authoritative nameservers **SHOULD** support UDP sufficiently according to the EDNS0 extended
package size and connectivity. Otherwise a corresponding **WARNING** is returned.

**WARNINGs**:
[cols="1,6"]
|===
|Code |Message

| 214
| Querying some authoritative nameservers via EDNS0 UDP yields truncation because of not supporting sufficient packet size. 

| 222
| Querying some authoritative nameservers via EDNS0 UDP yields timeout

| 224
| Querying some authoritative nameservers via EDNS0 UDP yields unreachable
|===

[[req:dnssec-cross-rrset,Availability of DNSKEY RRSet]]
===== Availability of DNSKEY RRSet
The DNSKEY RRSet **MUST** be retrievable from DNS via TCP or UDP with attached
DNSSEC signature data (EDNS0). Otherwise **ERROR**.

**ERRORs**:
[cols="1,6"]
|===
|Code |Message

| 215
| Timeout after switching from UDP to TCP - switch to TCP due to truncation

| 223
| Timeout after switching from UDP to TCP - switch to TCP due to timeout

| 225
| Timeout after switching from UDP to TCP

| 219
| Unable to retrieve DNSKEY RR with TCP or EDNS0
|===