=== Über dieses Dokument

Die vorliegende Dokumentation beschreibt die geltenden Anforderungen an Nameserver 
und Zonendaten, die erfüllt sein müssen, damit eine Domain von der DENIC an diese 
Nameserver delegiert werden kann. Die Policy und die damit verbundenen Checks werden 
hier dargestellt. 

=== Motivation

Das Domain Name System (DNS) ist ein hierarchisch aufgebauter, verteilter und replizierter 
Datenbestand zur Abbildung von Namen in Adressen und andere 
Internetinfrastrukturelemente. Hierarchie und Verteilung werden durch Delegationen 
implementiert. Direkt unterhalb der Wurzel des Namensraumes liegen die Top Level 
Domains (TLDs), deren Verwaltung u.a. durch das Dokument http://www.ietf.org/rfc/rfc4697.txt[RFC1591]
geregelt ist. Dem TLD-Verwalter obliegt die stabile, dem Stand der Technik entsprechende Pflege der 
Zonendaten und der best practices folgende Betrieb der entsprechenden Nameserver. 
 
Das DNS ist wegen seiner Verteilung und Redundanz hochgradig fehlertolerant. Es können 
jedoch durch Netzstörungen und Konfigurationsfehler Situationen entstehen, in denen 
Domains nicht oder falsch aufgelöst werden, siehe auch http://www.ietf.org/rfc/rfc4697.txt[RFC4697].
Der Internetnutzer bemerkt zwar die Fehlfunktion, kann die Ursache aber nicht immer im
DNS lokalisieren. In besonders ungünstigen Konstellationen können DNS-Fehlfunktionen zu
Störungen in Netzbereichen führen, die von der Ursache weder betroffen, noch für sie
verantwortlich sind, geschweige denn in der Lage wären, sie zu beseitigen. Im Interesse eines 
funktionierenden Gesamtsystems und eines nach außen wie innen stabil versorgten 
Namensraumes prüft die TLD-Verwaltung daher gewisse Voraussetzungen vor der 
Delegation, ohne deren Erfüllung eine Delegation nicht erfolgt. Darüber hinaus gibt es eine 
Reihe von Kriterien, die nicht absolut kritisch sind, deren Erfüllung aber die Dienstqualität 
verbessern kann.