{{- if not .Values.global.externalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name:  {{ include "nastng-docs.fullname" . }}
data:
  {{- toYaml .Values.secrets | nindent 2 }}
type: Opaque
{{- end }}
