replicaCount: 1

image:
  repository: registry.cloud.denic.de/teamdns/nastng-docs
  pullPolicy: Always

testConnection:
  enabled: false

vault:
  secrets: "nastng-docs"

global:
  externalSecrets:
    enabled: true
    approach: vault
