= Nameserver Predelegation Check

[.text-right]
xref:index.adoc#Predelegation-Check-Specification[EN]

Der Nameserver Predelegation Check beinhaltet die Verifikation von Nameservern und deren Konfiguration
hinsichtlich DNS basierter Zonen-Delegation. Hierbei werden die Nameserver einer bestimmten Zone (Domain)
verschiedenen Tests unterzogen, um sicherzustellen, dass sie korrekt konfiguriert sind, und die Domain sicher
und einfach delegiert werden kann. Damit wird ein hoher Grad an Qualität für die Domain erzielt. Die nachfolgenden
Referenzen sind wiefolgt gegliedert: Der Abschnitt <<Policy>> behandelt die eigentliche technische Anforderung
(Spezifikation) hinsichtlich der Namersever Konfiguration. Die Anwedung als eigenständiger
Service (bekannt als NASTng) wird in Abschnitt <<Service>> beschrieben.

== Policy
xref:spec/spec_de.adoc#Predelegation-Check-Specification[Beginnen Sie zum Einstieg mit dem Lesen der Spezifikation.]

== Service
xref:nast/nast_de.adoc#NAST---NameServer-Tester[Lernen Sie unseren NASTng Service kennen.]